### ISSUE TITLE
Serbia

### ISSUE THREAD

**Issue by vool** [Stroemgren/Laravel-Country-Seed#3]
Hi,

Just a heads up, the seed seems to be missing Serbia array ( 'code' => 'RS', 'name' => 'Serbia'),

I would issue a PR but I removed the ids on the countries on my fork, so might no suit

https://github.com/vool/Laravel-Country-Seed/blob/master/database/seeds/CountriesTableSeeder.php

Thanks for the seed.

Keith

**Comment by Stroemgren** [comment]
Thanks!

I've added it. 
835d7d859c8fb3781729ddf651d741f957240fbd
